# -*- coding: utf-8 -*-
"""analise_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NJf4-5lkbfSC8zZ2w1Zj-eqI9nS9y-I
"""

import pandas as pd
import json

LIMITE_SUSPEITO = 10000.00


def moeda(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


print("=" * 50)
print("ANÁLISE FINANCEIRA")
print("=" * 50)

try:
    df = pd.read_csv("transacoes.csv")
except FileNotFoundError:
    print("Arquivo transacoes.csv não encontrado.")
    exit()

total_linhas = len(df)



df["id"] = pd.to_numeric(df["id"], errors="coerce")
df["valor"] = pd.to_numeric(df["valor"], errors="coerce")
df["data"] = pd.to_datetime(df["data"], format="%Y-%m-%d", errors="coerce")

df["cliente_id"] = df["cliente_id"].fillna("").astype(str)

df = df[
    df["id"].notna()
    & (df["cliente_id"].str.strip() != "")
    & df["data"].notna()
    & df["tipo"].isin(["credito", "debito"])
    & df["valor"].notna()
    & (df["valor"] > 0)
]

linhas_validas = len(df)
linhas_invalidas = total_linhas - linhas_validas

print(f"Total de linhas lidas : {total_linhas}")
print(f"Linhas válidas        : {linhas_validas}")
print(f"Linhas inválidas      : {linhas_invalidas}")


df["mes"] = df["data"].dt.strftime("%Y-%m")


relatorio = []

for mes, grupo in df.groupby("mes"):

    total_credito = grupo.loc[
        grupo["tipo"] == "credito", "valor"
    ].sum()

    total_debito = grupo.loc[
        grupo["tipo"] == "debito", "valor"
    ].sum()

    saldo = total_credito - total_debito

    media = grupo["valor"].mean()

    maior = grupo["valor"].max()

    menor = grupo["valor"].min()

    quantidade = len(grupo)

    relatorio.append({
        "mes": mes,
        "quantidade": quantidade,
        "credito": total_credito,
        "debito": total_debito,
        "saldo": saldo,
        "media": media,
        "maior": maior,
        "menor": menor
    })


print("\n===== RELATÓRIO MENSAL =====")

for r in relatorio:

    print(f"\nMês: {r['mes']}")
    print(f"  Quantidade:      {r['quantidade']}")
    print(f"  Total Crédito:   {moeda(r['credito'])}")
    print(f"  Total Débito:    {moeda(r['debito'])}")
    print(f"  Saldo:           {moeda(r['saldo'])}")
    print(f"  Média:           {moeda(r['media'])}")
    print(f"  Maior valor:     {moeda(r['maior'])}")
    print(f"  Menor valor:     {moeda(r['menor'])}")



suspeitas = df[df["valor"] > LIMITE_SUSPEITO]

print("\n===== TRANSAÇÕES SUSPEITAS =====")

if suspeitas.empty:

    print("Nenhuma transação suspeita encontrada.")

else:

    for _, linha in suspeitas.iterrows():

        print(
            f"ID: {int(linha['id'])} | "
            f"Cliente: {linha['cliente_id']} | "
            f"Data: {linha['data'].strftime('%Y-%m-%d')} | "
            f"Valor: {moeda(linha['valor'])}"
        )


print("\n===== COMPARAÇÃO COM A SOLUÇÃO NATIVA =====")

try:

    with open("relatorio.json", "r", encoding="utf-8") as arquivo:
        relatorio_nativo = json.load(arquivo)

    if (
        relatorio_nativo["total_transacoes_validas"]
        == linhas_validas
    ):

        print("✔ Total de transações válidas é igual.")

    else:

        print("✘ Diferença encontrada no total de transações.")

    print("✔ Comparação realizada com sucesso.")

except FileNotFoundError:

    print(
        "Arquivo relatorio.json não encontrado.\n"
        "Execute primeiro a solução principal para realizar a comparação."
    )